apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-configmap
  namespace: default
data:
  PORT: 'REPLACE_PORT'
  NODE_ENV: 'REPLACE_NODE_ENV'
  AWSREGION: 'REPLACE_AWSREGION'
  AWS_S3_BUCKET_NAME: 'REPLACE_AWS_S3_BUCKET_NAME'
  LOCAL_ACCESS_TOKEN_VALIDITY : 'REPLACE_LOCAL_ACCESS_TOKEN_VALIDITY'
  LOCAL_REFRESH_TOKEN_VALIDITY : 'REPLACE_LOCAL_REFRESH_TOKEN_VALIDITY'
  KMS_KEYID: 'REPLACE_KMS_KEYID'
  KMS_MASTER_KEY: 'REPLACE_KMS_MASTER_KEY'

    
